version: "3.8"
services:
  db:
    image: mysql
    volumes:
      - data:/data/db
    env_file:
      - ./env/mysql.env
  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - logs:/app/logs
      - ./app:/app
      - /app/node_modules
    depends_on:
      - db
volumes:
  data:
  logs:
